### ISSUE TITLE
Inserir LightBox

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/relatos-wp-plugin#17]
Olá @wilsonmoura, por favor inserir recurso de lightbox na sessão de imagens.
Grato!

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor atualizar ambiente local e validar.

**Comment by marcioalvessilva** [comment]
@wilsonmoura essa etapa foi concluída.
Grato!
