### ISSUE TITLE
Na página de configuração do plugin, incluir campo para aplicar cor customizada nos templates

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/relatos-wp-plugin#19]
Aplicar cor customizada nos elementos abaixo:

Ex: 
.box1 h4
**background: linear-gradient(328deg, #2482a0 0%, #73a0be 100%);**
![image](https://user-images.githubusercontent.com/48724136/210398238-f5b8199e-c68b-426b-8602-6d5825e25b92.png)

.title2
**color: #2482a0;**

.title2::after
**background: linear-gradient(328deg, #d2d2d2 0%, #2482a0 100%);**
![image](https://user-images.githubusercontent.com/48724136/210401899-6ada4493-8c36-40b1-842e-0d0cea7f4d78.png)

#title-relatos
**background: #2482a0;**
![image](https://user-images.githubusercontent.com/48724136/210403045-3088cde1-2a2f-4d21-8fc2-ee3084d4913e.png)

#accordionArchive .card-header{
**border-left: 3px solid #2482a0 ;**
![image](https://user-images.githubusercontent.com/48724136/210558135-576fb579-8b10-45ca-96f9-6f8f31931ad6.png)

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor validar.

**Comment by marcioalvessilva** [comment]
Estou analisando esse  efeito colateral, quero verificar se isso pode acontecer em outros temas
![image](https://user-images.githubusercontent.com/48724136/210805388-a0f7f249-f0e8-44cf-aa60-8bf622b76436.png)

**Comment by marcioalvessilva** [comment]
Fiz ajuste no CSS para correção da área do Accordion, 
GitHub Atualizado, por favor sincronizar para eu conseguir validar

**Comment by wilsonmoura** [comment]
@marcioalvessilva plugin atualizado conforme solicitado. Favor validar.

**Comment by marcioalvessilva** [comment]
Concluído! Grato!
