### ISSUE TITLE
Na interface do plugin falta uma identificação de que o resultado de busca apresentado é referente a uma coleção de relatos de experiência

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-wp-plugin#22]
https://sms.sp-new.teste.bvs.br/relatos/

![image](https://user-images.githubusercontent.com/19578003/219657170-2a27be26-c0d4-4977-b3cb-15e126394152.png)

**Comment by marcioalvessilva** [comment]
Inserido
![image](https://user-images.githubusercontent.com/48724136/221966431-f99864bb-2aa8-40b6-a461-5dbac51ffb6c.png)

**Comment by wilsonmoura** [comment]
Ajustes realizados pelo @marcioalvessilva em 06641ecaa4756b80a0bc3271215577934a8d1544
