### ISSUE TITLE
Ocultar campos quando não existirem dados e gerar pdf em botão de documentos

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/relatos-wp-plugin#23]
**Ocultar campos caso não exista dados (Vídeos, Fotos e Outras Mídias)**
![image](https://user-images.githubusercontent.com/48724136/221966731-a9a0bec0-2690-4c79-a1c5-04ea78574007.png)
![image](https://user-images.githubusercontent.com/48724136/221966841-35a9b63c-f2b9-4a02-8c6c-3006b4d57d3d.png)

**Gerar PDF para download**
![image](https://user-images.githubusercontent.com/48724136/221967051-863b8d53-21bb-40a8-9fd9-990f85b2b638.png)

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor validar.

**Comment by marcioalvessilva** [comment]
Validado!
