### ISSUE TITLE
Relato disponível no plugin, mesmo sendo desmarcado no módulo de admin

### ISSUE THREAD

**Issue by marcoslmori** [bireme/relatos-wp-plugin#29]
![image](https://github.com/bireme/relatos-wp-plugin/assets/10047460/6d53f4cb-5566-4f02-b28a-d95e575b4bcd)

Esse relato que está em amarelo, foi desmarcado da coleção da BVS SMS
https://sms.sp.bvs.br/relatos

Mas ainda continua aparecendo. 
e so pertence a essas coleções abaixo

![image](https://github.com/bireme/relatos-wp-plugin/assets/10047460/44027326-a2c7-48d6-aa09-4d6cad16f7ad)

Observação:  plugin atualizado.

Pode verificar se é problema do plugin ou do processo?  

Abraços,

**Comment by wilsonmoura** [comment]
@marcoslmori a atualização do índice de pesquisa do plugin é realizado via agendamento diário no final do dia.

**Comment by barrosjo** [comment]
@wilsonmoura esse mesmo registro foi excluído na semana passada da plataforma e ainda aparece na interface de pesquisa do plugin https://mtci.bvsalud.org/relatos/

**Comment by wilsonmoura** [comment]
@barrosjo normalizamos o repositório do plugin na BVS MTCI, pois identificamos que o mesmo estava com as configurações do ambiente de testes. Favor validar.
@marcoslmori antes de solicitar a transferência de plugins entre servidores, recomendamos sempre verificar se existem modificações no repositório local para garantir que o respectivo plugin funcione corretamente no servidor de destino. Para isso, basta executar o comando `git status` dentro da pasta do plugin para verificar se existem modificações nos arquivos do repositório desse plugin.

**Comment by marcoslmori** [comment]
@wilsonmoura o cheque de atualizações e atualização, sempre é verificado antes de ir para a produção

**Comment by wilsonmoura** [comment]
@marcoslmori nesse caso, o problema não foi de atualização, e sim devido a modificações locais no ambiente de testes que foram transferidas ao ambiente de produção.
