### ISSUE TITLE
Criar campo para troca de imagem 

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/relatos-wp-plugin#34]
@wilsonmoura, por favor verificar a possibilidade de criar campo para troca de imagem titulo, diferente a ultima solicitação agora o desejo é que seja alterado por plugin instalado. assim como é feito no campo de cores. 
A ideia é que cada instancia tenha uma imagem padrão e permita que seja alterado.

Essa imagem
![image](https://github.com/bireme/relatos-wp-plugin/assets/48724136/1db3f2c9-cb44-4eea-87ec-f0de146c6dd3)

Campo cor
![image](https://github.com/bireme/relatos-wp-plugin/assets/48724136/5b33438a-bbea-4f69-b792-08842e0bed10)
Qualquer dúvida estou à disposição

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor validar.

**Comment by marcioalvessilva** [comment]
Concluído, grato!
