### ISSUE TITLE
A labels dos campos estão em inglês no plugin relatos da BVS MTCI na interface da BVS em espanhol. Na interface em português as labels estão corretamente em PT.

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-wp-plugin#37]
Ex: https://mtci.bvsalud.org/relatos/resource/?id=43 (ano mudar o idioma da interface é identificado o problema

**Comment by barrosjo** [comment]
@wilsonmoura alguma atualização sobre esse problema?

**Comment by wilsonmoura** [comment]
@barrosjo segue lista dos textos que devem ser traduzidos para o idioma espanhol: [relatos.txt](https://github.com/bireme/relatos-wp-plugin/files/12366350/relatos.txt)

Favor colocar a tradução de cada linha na frente do respectivo texto. Após finalizar, anexar o arquivo atualizado nesse issue.

**Comment by barrosjo** [comment]
@wilsonmoura segue arquivo com a respectiva tradução
[relatos.txt](https://github.com/bireme/relatos-wp-plugin/files/12500796/relatos.txt)

**Comment by wilsonmoura** [comment]
@barrosjo ajustes realizados. Favor validar.

**Comment by barrosjo** [comment]
@wilsonmoura os textos continuam em inglês
